"""
NovaMart Financial Ledger Chart of Accounts & Tax Calculation Engine
====================================================================
Comprehensive double-entry general ledger chart of accounts, statutory tax rules,
and merchant fee schedules across all 500+ Indian e-commerce categories.
"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, List, Optional


@dataclass
class GeneralLedgerAccount:
    account_code: str
    account_name: str
    account_type: str # 'ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'
    description: str
    is_reconciliation_required: bool


# Chart of Accounts
CHART_OF_ACCOUNTS: List[GeneralLedgerAccount] = [
    GeneralLedgerAccount("1010", "Nodal Escrow Bank Account (HDFC Pool)", "ASSET", "Central escrow account holding buyer funds", True),
    GeneralLedgerAccount("1020", "Operational Bank Account (ICICI Main)", "ASSET", "Corporate operating account for fee collections", True),
    GeneralLedgerAccount("1030", "Payment Gateway Clearing Account (Razorpay)", "ASSET", "In-transit clearing from online payment gateways", True),
    GeneralLedgerAccount("1040", "Payment Gateway Clearing Account (PayU)", "ASSET", "In-transit clearing from PayU gateway", True),
    GeneralLedgerAccount("1050", "COD Cash Clearing Account (Ekart Courier)", "ASSET", "In-transit cash collected by delivery executives", True),
    GeneralLedgerAccount("2010", "Merchant Payable Escrow Ledger", "LIABILITY", "Net payable balance owed to registered sellers", True),
    GeneralLedgerAccount("2020", "Output GST Payable (18% on Platform Fee)", "LIABILITY", "GST liability to be deposited to Government", True),
    GeneralLedgerAccount("2030", "Section 52 TCS Payable (1% on Net Sales)", "LIABILITY", "Tax Collection at Source payable to GSTN", True),
    GeneralLedgerAccount("2040", "Section 194-O TDS Payable (1% on Gross GMV)", "LIABILITY", "Income Tax withholding payable via NSDL", True),
    GeneralLedgerAccount("2050", "Customer Wallet & SuperCoin Liability", "LIABILITY", "Outstanding customer reward points balance", True),
    GeneralLedgerAccount("4010", "Marketplace Commission Revenue", "REVENUE", "Platform take-rate commission on completed sales", False),
    GeneralLedgerAccount("4020", "Sponsored Product Listing Ads Revenue", "REVENUE", "Seller advertising CPC click revenues", False),
    GeneralLedgerAccount("4030", "Logistics Freight Revenue Recovery", "REVENUE", "Shipping fees billed to customers and sellers", False),
    GeneralLedgerAccount("5010", "Payment Gateway Transaction Fees", "EXPENSE", "MDR processing fees paid to gateways", False),
    GeneralLedgerAccount("5020", "3PL Courier Freight Expense", "EXPENSE", "Actual transportation charges paid to couriers", False),
    GeneralLedgerAccount("5030", "Customer Compensation & Goodwill Discretionary", "EXPENSE", "Appeasement vouchers for customer escalation", False),
]


@dataclass
class CategoryCommissionFeeSchedule:
    category_id: int
    category_name: str
    base_commission_percent: Decimal
    closing_fee_fixed_inr: Decimal
    payment_collection_fee_percent: Decimal
    return_shipping_fee_inr: Decimal


CATEGORY_FEE_SCHEDULES: List[CategoryCommissionFeeSchedule] = [
    CategoryCommissionFeeSchedule(
        category_id=1,
        category_name="Category Node 1 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=2,
        category_name="Category Node 2 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=3,
        category_name="Category Node 3 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=4,
        category_name="Category Node 4 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=5,
        category_name="Category Node 5 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=6,
        category_name="Category Node 6 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=7,
        category_name="Category Node 7 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=8,
        category_name="Category Node 8 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=9,
        category_name="Category Node 9 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=10,
        category_name="Category Node 10 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=11,
        category_name="Category Node 11 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=12,
        category_name="Category Node 12 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=13,
        category_name="Category Node 13 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=14,
        category_name="Category Node 14 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=15,
        category_name="Category Node 15 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=16,
        category_name="Category Node 16 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=17,
        category_name="Category Node 17 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=18,
        category_name="Category Node 18 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=19,
        category_name="Category Node 19 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=20,
        category_name="Category Node 20 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=21,
        category_name="Category Node 21 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=22,
        category_name="Category Node 22 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=23,
        category_name="Category Node 23 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=24,
        category_name="Category Node 24 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=25,
        category_name="Category Node 25 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=26,
        category_name="Category Node 26 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=27,
        category_name="Category Node 27 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=28,
        category_name="Category Node 28 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=29,
        category_name="Category Node 29 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=30,
        category_name="Category Node 30 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=31,
        category_name="Category Node 31 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=32,
        category_name="Category Node 32 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=33,
        category_name="Category Node 33 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=34,
        category_name="Category Node 34 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=35,
        category_name="Category Node 35 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=36,
        category_name="Category Node 36 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=37,
        category_name="Category Node 37 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=38,
        category_name="Category Node 38 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=39,
        category_name="Category Node 39 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=40,
        category_name="Category Node 40 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=41,
        category_name="Category Node 41 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=42,
        category_name="Category Node 42 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=43,
        category_name="Category Node 43 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=44,
        category_name="Category Node 44 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=45,
        category_name="Category Node 45 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=46,
        category_name="Category Node 46 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=47,
        category_name="Category Node 47 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=48,
        category_name="Category Node 48 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=49,
        category_name="Category Node 49 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=50,
        category_name="Category Node 50 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=51,
        category_name="Category Node 51 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=52,
        category_name="Category Node 52 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=53,
        category_name="Category Node 53 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=54,
        category_name="Category Node 54 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=55,
        category_name="Category Node 55 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=56,
        category_name="Category Node 56 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=57,
        category_name="Category Node 57 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=58,
        category_name="Category Node 58 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=59,
        category_name="Category Node 59 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=60,
        category_name="Category Node 60 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=61,
        category_name="Category Node 61 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=62,
        category_name="Category Node 62 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=63,
        category_name="Category Node 63 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=64,
        category_name="Category Node 64 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=65,
        category_name="Category Node 65 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=66,
        category_name="Category Node 66 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=67,
        category_name="Category Node 67 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=68,
        category_name="Category Node 68 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=69,
        category_name="Category Node 69 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=70,
        category_name="Category Node 70 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=71,
        category_name="Category Node 71 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=72,
        category_name="Category Node 72 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=73,
        category_name="Category Node 73 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=74,
        category_name="Category Node 74 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=75,
        category_name="Category Node 75 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=76,
        category_name="Category Node 76 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=77,
        category_name="Category Node 77 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=78,
        category_name="Category Node 78 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=79,
        category_name="Category Node 79 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=80,
        category_name="Category Node 80 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=81,
        category_name="Category Node 81 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=82,
        category_name="Category Node 82 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=83,
        category_name="Category Node 83 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=84,
        category_name="Category Node 84 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=85,
        category_name="Category Node 85 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=86,
        category_name="Category Node 86 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=87,
        category_name="Category Node 87 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=88,
        category_name="Category Node 88 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=89,
        category_name="Category Node 89 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=90,
        category_name="Category Node 90 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=91,
        category_name="Category Node 91 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=92,
        category_name="Category Node 92 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=93,
        category_name="Category Node 93 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=94,
        category_name="Category Node 94 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=95,
        category_name="Category Node 95 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=96,
        category_name="Category Node 96 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=97,
        category_name="Category Node 97 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=98,
        category_name="Category Node 98 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=99,
        category_name="Category Node 99 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=100,
        category_name="Category Node 100 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=101,
        category_name="Category Node 101 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=102,
        category_name="Category Node 102 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=103,
        category_name="Category Node 103 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=104,
        category_name="Category Node 104 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=105,
        category_name="Category Node 105 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=106,
        category_name="Category Node 106 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=107,
        category_name="Category Node 107 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=108,
        category_name="Category Node 108 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=109,
        category_name="Category Node 109 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=110,
        category_name="Category Node 110 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=111,
        category_name="Category Node 111 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=112,
        category_name="Category Node 112 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=113,
        category_name="Category Node 113 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=114,
        category_name="Category Node 114 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=115,
        category_name="Category Node 115 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=116,
        category_name="Category Node 116 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=117,
        category_name="Category Node 117 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=118,
        category_name="Category Node 118 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=119,
        category_name="Category Node 119 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=120,
        category_name="Category Node 120 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=121,
        category_name="Category Node 121 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=122,
        category_name="Category Node 122 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=123,
        category_name="Category Node 123 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=124,
        category_name="Category Node 124 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=125,
        category_name="Category Node 125 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=126,
        category_name="Category Node 126 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("11.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=127,
        category_name="Category Node 127 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("12.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=128,
        category_name="Category Node 128 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("13.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=129,
        category_name="Category Node 129 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("14.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=130,
        category_name="Category Node 130 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("15.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=131,
        category_name="Category Node 131 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("16.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("56.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=132,
        category_name="Category Node 132 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("17.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("57.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=133,
        category_name="Category Node 133 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("18.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("58.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=134,
        category_name="Category Node 134 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("19.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("59.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=135,
        category_name="Category Node 135 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("20.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("60.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=136,
        category_name="Category Node 136 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("21.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("61.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=137,
        category_name="Category Node 137 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("22.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("62.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=138,
        category_name="Category Node 138 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("23.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("63.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=139,
        category_name="Category Node 139 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("24.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("64.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=140,
        category_name="Category Node 140 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("25.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("45.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=141,
        category_name="Category Node 141 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("6.5"),
        closing_fee_fixed_inr=Decimal("26.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("46.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=142,
        category_name="Category Node 142 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("7.5"),
        closing_fee_fixed_inr=Decimal("27.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("47.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=143,
        category_name="Category Node 143 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("8.5"),
        closing_fee_fixed_inr=Decimal("28.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("48.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=144,
        category_name="Category Node 144 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("9.5"),
        closing_fee_fixed_inr=Decimal("29.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("49.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=145,
        category_name="Category Node 145 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("10.5"),
        closing_fee_fixed_inr=Decimal("30.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("50.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=146,
        category_name="Category Node 146 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("11.5"),
        closing_fee_fixed_inr=Decimal("31.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("51.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=147,
        category_name="Category Node 147 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("12.5"),
        closing_fee_fixed_inr=Decimal("32.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("52.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=148,
        category_name="Category Node 148 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("13.5"),
        closing_fee_fixed_inr=Decimal("33.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("53.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=149,
        category_name="Category Node 149 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("14.5"),
        closing_fee_fixed_inr=Decimal("34.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("54.00"),
    ),
    CategoryCommissionFeeSchedule(
        category_id=150,
        category_name="Category Node 150 - Industrial & Consumer Goods",
        base_commission_percent=Decimal("5.5"),
        closing_fee_fixed_inr=Decimal("10.00"),
        payment_collection_fee_percent=Decimal("2.0"),
        return_shipping_fee_inr=Decimal("55.00"),
    ),
]
